Mirroring Xenomai git repositories with grokmirror
==================================================
:revdate:	October 8, 2015
:author:	Gilles Chanteperdrix
:categories:	Benchmark
:tags:		git

You can mirror Xenomai git repositories using the tool named
https://github.com/mricon/grokmirror[grokmirror]. xenomai.org manifest is
available at the following addresses:

http://git.xenomai.org/manifest.js.gz

https://git.xenomai.org/manifest.js.gz

You will find general information on how to install and use grokmirror at the
following addresses:

https://github.com/mricon/grokmirror

https://www.kernel.org/mirroring-kernelorg-repositories.html

If you are interested in Xenomai server-side setup, see
https://click-hack.org/git-server-howto.html#_installing_and_configuring_grokmirror[this
page].

But we provide here examples for two common configurations.


With only one ipipe git
-----------------------

In order to avoid duplication, all I-pipe git repositories make reference to the
kernel.org/linux-stable repository. But if you are mirroring only one I-pipe
git, (for instance the reference ipipe.git repository), you can configure
grokmirror to ignore the reference and not download the linux-stable git.

The following configuration file does this:
-------------------------------------------------------------------------------
[xenomai.org]
site = git://git.xenomai.org
manifest = http://git.xenomai.org/manifest.js.gz
default_owner = Grokmirror User
toplevel = /var/lib/git/mirror
mymanifest = /var/lib/git/mirror/manifest.js.gz
log = /var/log/mirror/xenomaiorg.log
loglevel = info
lock = /var/lock/mirror/kernelorg.lock
include = /ipipe.git
exclude =
ignore_repo_references=yes
-------------------------------------------------------------------------------

With multiple ipipe git
-----------------------

If you want to mirror multiple ipipe git (for instance ipipe.git and
ipipe-jki.git), you should remove ignore_repo_references, and add the
linux-stable.git repository to the list. The following configuration file does
this.

-------------------------------------------------------------------------------
[xenomai.org]
site = git://git.xenomai.org
manifest = http://git.xenomai.org/manifest.js.gz
default_owner = Grokmirror User
toplevel = /var/lib/git/mirror
mymanifest = /var/lib/git/mirror/manifest.js.gz
log = /var/log/mirror/xenomaiorg.log
loglevel = info
lock = /var/lock/mirror/kernelorg.lock
include = /kernel.org/linux-stable.git
	/ipipe.git
	/ipipe-jki.git
exclude =
-------------------------------------------------------------------------------
