Xenomai history
===============

Originally named _Xenodaptor_, the project that would soon become
Xenomai http://www.mail-archive.com/rtl@fsmlabs.com/msg01156.html[was
announced] on August 2001 by mailto:rpm@xenomai.org[Philippe
Gerum]. The
http://lists.gnu.org/archive/html/xenomai-main/2002-03/msg00000.html[Xenomai
1.0 milestone] was reached in March 2002.

In its early days, Xenomai used to be an add-on component to real-time
Linux variants for emulating traditional RTOS, originally based on a
dual kernel approach. Over the years, it has become a full-fledged
real-time Linux framework on its own terms, also available on
single/native kernel systems.

link:Getting_The_I_Pipe_Patch[Adeos/I-pipe] is a companion project to
Xenomai, which implements a key component of a dual kernel
configuration: the interrupt virtualization mechanism delivering high
priority events to the Xenomai co-kernel with short and predictable
latencies. Xenomai was the first real-time extension to be
http://marc.info/?l=linux-kernel&m=102694301104746&w=2[ported over the
I-pipe], followed a year after by
http://article.gmane.org/gmane.linux.real-time.rtai/3248[RTAI].

In the 2003-2005 period, the original core team members - namely
link:Gilles_Chanteperdrix[Gilles Chanteperdrix] and
mailto:rpm@xenomai.org[Philippe Gerum] - contributed significantly to
the https://lwn.net/Articles/61013/[RTAI project], before focusing
back on Xenomai's own goals, which led to the release of Xenomai 2.0
in October 2005.

Since then, Xenomai has been actively maintained and ported to various
CPU architectures, for a user base mainly involved in the industrial
automation industry.
